# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Shawn
tagline:          'Shaligram'
description:      'Personal Blog on QA Automation'
url:              http://shaligramk.github.io

author:
  name:           'Shawn Shaligram'
  url:            https://twitter.com/shaligramk

paginate:         5

# Custom vars
version:          2.0.0

